<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.5.1 on win32)" generated="20200730 17:13:23.547" rpa="false">
<suite id="s1" source="D:\selenium" name="Selenium">
<suite id="s1-s1" source="D:\selenium\first.robot" name="First">
<test id="s1-s1-t1" name="首页按钮跳转">
<kw name="Open Browser">
<arguments>
<arg>https://bimface.com</arg>
<arg>chrome</arg>
</arguments>
<msg level="FAIL" timestamp="20200730 17:13:23.699">No keyword with name 'Open Browser' found.</msg>
<status starttime="20200730 17:13:23.699" status="FAIL" endtime="20200730 17:13:23.699"></status>
</kw>
<tags>
<tag>DEBUG</tag>
</tags>
<status starttime="20200730 17:13:23.697" critical="yes" status="FAIL" endtime="20200730 17:13:23.700">No keyword with name 'Open Browser' found.</status>
</test>
<status starttime="20200730 17:13:23.574" status="FAIL" endtime="20200730 17:13:23.700"></status>
</suite>
<status starttime="20200730 17:13:23.549" status="FAIL" endtime="20200730 17:13:23.701"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">DEBUG</stat>
</tag>
<suite>
<stat id="s1" name="Selenium" pass="0" fail="1">Selenium</stat>
<stat id="s1-s1" name="First" pass="0" fail="1">Selenium.First</stat>
</suite>
</statistics>
<errors>
<msg level="ERROR" timestamp="20200730 17:13:23.696">Error in file 'D:\selenium\first.robot' on line 2: Initializing test library 'SeleniumLibrary' with arguments [ a.txt ] failed: ValueError: Invalid time string 'a.txt'.
Traceback (most recent call last):
  File "d:\program files\lib\site-packages\SeleniumLibrary\__init__.py", line 432, in __init__
    self.timeout = timestr_to_secs(timeout)
  File "d:\program files\lib\site-packages\robot\utils\robottime.py", line 48, in timestr_to_secs
    raise ValueError("Invalid time string '%s'." % timestr)</msg>
</errors>
</robot>
